/* 
  A Javascript file that generates a table based on user input.
  The user input being game type, if it's open world, and if there's DLC.
*/

/*
  Gets the values of the selected items in the dropdown menu.
  Assigns numbers to variables based on these values, then calculates the total hours needed.
*/
function calculateHours() {
    "use strict";
    
    var type, world, dlc, hours, multiplier, addition, totalHours;
    
    type = document.getElementById("GameType").selectedIndex;
    world = document.getElementById("OpenWorld").selectedIndex;
    dlc = document.getElementById("ExtraContent").selectedIndex;
    
    if (type === 0) { hours = 1000; }
    if (type === 1) { hours = 150; }
    if (type === 2) { hours = 300; }
    if (type === 3) { hours = 100; }
    
    if (world === 0) { multiplier = 3; }
    if (world === 1) { multiplier = 1; }
    
    if (dlc === 0) { addition = 80; }
    if (dlc === 1) { addition = 0; }
        
    totalHours = hours * multiplier + addition;
    return totalHours;
}

/*
  Generates a comment on the total amount of hours needed to finish a game depending on the amount of hours
*/
function generateComment() {
    "use strict";
    var comment, hours = calculateHours();
    
    if (hours < 150) { comment = "Well that should take no time at all!"; }
    if (hours >= 150 && hours <= 300) { comment = "A decently sized game it apperas."; }
    if (hours > 300 && hours < 500) { comment = "Well that should take a while."; }
    if (hours > 500 && hours < 1000) { comment = "Ok, that's getting excessive."; }
    if (hours > 1000) { comment = "You'll never finish this game! Muahahaha!"; }
    
    
    return comment;
}

/*
  Generates a list with the results generated above
*/
function generateList(Hours, Comment) {
    "use strict";
    
    $("#resultTable").html(" <dl><dt>Hours Needed</dt><dd>" + Hours + "</dd><dt>Associated comment</dt><dd>" + Comment + "</dd></dl> ");
    
}

/*
  The "main" method that runs the javascript and outputs it to the page.
  The event listener is a 'submit' action generated by clicking the submit button on the html page.
*/
$('#hoursNeeded').submit(function (event) {
  event.preventDefault();
  "use strict";
  $('#resultTable').empty();
  generateList(calculateHours(), generateComment());
    
});